[[redirects]]
    from = "https://fredtunleirsted.no/*"
    to = "https://fredtun.org/:splat"
    status = 301
    force = true
[[redirects]]
    from = "http://fredtunleirsted.no/*"
    to = "http://fredtun.org/:splat"
    status = 301
    force = true
[[redirects]]
    from = "https://fredtun.netlify.app/*"
    to = "https://fredtun.org/:splat"
    status = 301
    force = true
    
[[redirects]]
    from = "/blog/*"
    to = "/blogg/:splat"
    status = 301
    
[[redirects]]
    from = "/utleie/*"
    to = "/leie/:splat"
    status = 301

[[redirects]]
    from = "/personvernerklæring"
    to = "/personvernerklaering"
    status = 301

[[redirects]]
    from = "/personvernerkl%C3%A6ring"
    to = "/personvernerklaering"
    status = 301

[[redirects]]
    from = "/fast-giver/avtalevilkår"
    to = "/fast-giver/avtalevilkar"
    status = 301

[[redirects]]
    from = "/fast-giver/avtalevilk%C3%A5r"
    to = "/fast-giver/avtalevilkar"
    status = 301
