[[redirects]]
    from = "https://fredtunleirsted.no/*"
    to = "https://fredtun.org/:splat"
    status = 301
    force = true
[[redirects]]
    from = "http://fredtunleirsted.no/*"
    to = "http://fredtun.org/:splat"
    status = 301
    force = true
[[redirects]]
    from = "https://fredtun.netlify.app/*"
    to = "https://fredtun.org/:splat"
    status = 301
    force = true
    
[[redirects]]
    from = "/blog/*"
    to = "/blogg/:splat"
    status = 301
    
[[redirect]]
    from = "/utleie"
    to = "/leie"
    status = 301
